---
- :key: :water
  :japanese_name: "水"
  :english_name: water
  :specific_gravity: 1.0
  :synonyms: []
- :key: :sake
  :japanese_name: "酒"
  :english_name: sake
  :specific_gravity: 1.0
  :synonyms:
  - "日本酒"
- :key: :wine
  :japanese_name: "ワイン"
  :english_name: wine
  :specific_gravity: 1.0
  :synonyms: []
- :key: :vinegar
  :japanese_name: "酢"
  :english_name: vinegar
  :specific_gravity: 1.0
  :synonyms: []
- :key: :soy_source
  :japanese_name: "しょうゆ"
  :english_name: soy source
  :specific_gravity: 1.15
  :synonyms:
  - "醤油"
- :key: :sweet_sake
  :japanese_name: "本みりん"
  :english_name: sweet dake
  :specific_gravity: 1.15
  :synonyms:
  - "味醂"
- :key: :fake_sweet_sake
  :japanese_name: "みりん風調味料"
  :english_name: fake sweet sake
  :specific_gravity: 1.25
  :synonyms: []
- :key: :soybean_paste
  :japanese_name: "みそ"
  :english_name: soybean paste
  :specific_gravity: 1.15
  :synonyms:
  - "味噌"
- :key: :sea_salt
  :japanese_name: "粗塩"
  :english_name: sea salt
  :specific_gravity: 0.9
  :synonyms:
  - "あら塩"
- :key: :salt
  :japanese_name: "食塩"
  :english_name: salt
  :specific_gravity: 1.2
  :synonyms:
  - "塩"
- :key: :refined_salt
  :japanese_name: "精製塩"
  :english_name: refined salt
  :specific_gravity: 1.2
  :synonyms:
  - "焼き塩"
- :key: :castor_sugar
  :japanese_name: "上白糖"
  :english_name: castor sugar
  :specific_gravity: 0.65
  :synonyms:
  - "砂糖"
- :key: :granulated_sugar
  :japanese_name: "グラニュー糖"
  :english_name: granulated sugar
  :specific_gravity: 0.9
  :synonyms: []
- :key: :brown_sugar
  :japanese_name: "ざらめ"
  :english_name: brown sugar
  :specific_gravity: 1.0
  :synonyms:
  - "粗目"
- :key: :starch_syrup
  :japanese_name: "水あめ"
  :english_name: starch syrup
  :specific_gravity: 1.4
  :synonyms:
  - "水飴"
- :key: :honey
  :japanese_name: "はちみつ"
  :english_name: honey
  :specific_gravity: 1.4
  :synonyms:
  - "蜂蜜"
- :key: :jam
  :japanese_name: "ジャム"
  :english_name: jam
  :specific_gravity: 1.25
  :synonyms:
  - "ママレード"
- :key: :marmalade
  :japanese_name: "マーマレード"
  :english_name: marmalade
  :specific_gravity: 1.35
  :synonyms: []
- :key: :oil
  :japanese_name: "油"
  :english_name: oil
  :specific_gravity: 0.9
  :synonyms:
  - "サラダ油"
  - "サラダオイル"
  - "オリーブオイル"
  - "オイル"
- :key: :butter
  :japanese_name: "バター"
  :english_name: butter
  :specific_gravity: 0.9
  :synonyms: []
- :key: :margarine
  :japanese_name: "マーガリン"
  :english_name: margarine
  :specific_gravity: 0.9
  :synonyms: []
- :key: :lard
  :japanese_name: "ラード"
  :english_name: lard
  :specific_gravity: 0.85
  :synonyms: []
- :key: :shortening
  :japanese_name: "ショートニング"
  :english_name: shortening
  :specific_gravity: 0.8
  :synonyms: []
- :key: :cornstarch
  :japanese_name: "コーンスターチ"
  :english_name: cornstarch
  :specific_gravity: 0.5
  :synonyms:
  - "コーングリッツ"
  - "コーンフラワー"
  - "コーンミール"
- :key: :flour
  :japanese_name: "小麦粉"
  :english_name: flour
  :specific_gravity: 0.55
  :synonyms:
  - strong_flour
  - medium_flour
  - weak_flour
- :key: :starch
  :japanese_name: "片栗粉"
  :english_name: starch
  :specific_gravity: 0.65
  :synonyms: []
- :key: :milk
  :japanese_name: "牛乳"
  :english_name: milk
  :specific_gravity: 1.05
  :synonyms:
   - "ミルク"
- :key: :cream
  :japanese_name: "生クリーム"
  :english_name: cream
  :specific_gravity: 1.0
  :synonyms: []
- :key: :ketchup
  :japanese_name: "ケチャップ"
  :english_name: ketchup
  :specific_gravity: 1.15
  :synonyms:
  - "トマトケチャップ"
- :key: :worcestershire_sauce
  :japanese_name: "ウスターソース"
  :english_name: worcestershire sauce
  :specific_gravity: 1.2
  :synonyms:
  - "ソース"
- :key: :mayonnaise
  :japanese_name: "マヨネーズ"
  :english_name: mayonnaise
  :specific_gravity: 1.0
  :synonyms:
  - "マヨ"
